apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-application
  namespace: monitoring
spec:
  project: default
  source:
    repoURL: 'https://github.com/vkazmin1/client-A.git'
    targetRevision: main
    path: /overlays/dev/argocd/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
