apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-application
  namespace: monitoring
spec:
  project: default
  source:
    repoURL: 'https://github.com/vkazmin1/kustomize-example.git'
    targetRevision: main
    path: overlays/dev/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
