apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/vkazmin1/kustomize-example.git'
    targetRevision: main
    path: overlays/dev/grafana/
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
